feat: Add interactive SSH configuration creation to taskfile
This commit enhances the `taskfile.git.yaml` by introducing an interactive prompt that allows users to create an SSH configuration for their git provider. If the user opts to create the configuration, they can input their SSH public key, which is then added to the configuration file, streamlining the setup process for SSH key management.

diff --git a/taskfile.git.yaml b/taskfile.git.yaml
--- a/taskfile.git.yaml
+++ b/taskfile.git.yaml
@@ -59,3 +59,20 @@ tasks:
         echo
         echo "  $GIT_ROOT/$git_provider/$org_name/config"
         echo "  $GIT_ROOT/$git_provider/$org_name/key.pub"
+        echo
+        create_key=$(gum confirm "Create configuration now?")
+        if [ "$create_key" = "yes" ]; then
+          ssh_key=$(gum input --placeholder "Enter the ssh public key")
+          if [ -z "$ssh_key" ]; then
+            echo "Aborting"
+            exit 1
+          fi
+          cat <<EOF >> $GIT_ROOT/$git_provider/$org_name/config
+          Host $git_provider
+            HostName $git_provider
+            User git
+            IdentityFile $GIT_ROOT/$git_provider/$org_name/key.pub
+            IdentitiesOnly yes
+          EOF
+          echo "Created ssh config."
+        fi
