refactor: Update SSH configuration creation logic in taskfile
This commit modifies the SSH configuration creation process in `taskfile.git.yaml` by changing the confirmation prompt to abort on a "no" response. It also ensures that the SSH public key input is always requested, streamlining the configuration setup and improving user experience.

diff --git a/taskfile.git.yaml b/taskfile.git.yaml
--- a/taskfile.git.yaml
+++ b/taskfile.git.yaml
@@ -60,21 +60,23 @@ tasks:
         echo "  $GIT_ROOT/$git_provider/$org_name/config"
         echo "  $GIT_ROOT/$git_provider/$org_name/key.pub"
         echo
-        create_key=$(gum confirm "Create configuration now?")
-        if [ "$create_key" = "yes" ]; then
-          ssh_key=$(gum input --placeholder "Enter the ssh public key")
-          if [ -z "$ssh_key" ]; then
+        create_config=$(gum confirm "Create configuration now?")
+        if [ "$create_config" = "no" ]; then
+          echo "Aborting"
+          exit 1
+        fi
+        ssh_key=$(gum input --placeholder "Enter the ssh public key")
+        if [ -z "$ssh_key" ]; then
             echo "Aborting"
             exit 1
-          fi
-          bash -c '
-          cat <<EOF >> $GIT_ROOT/$git_provider/$org_name/config
-          Host $git_provider
-            HostName $git_provider
-            User git
-            IdentityFile $GIT_ROOT/$git_provider/$org_name/key.pub
-            IdentitiesOnly yes
-          EOF
-          '
-          echo "Created ssh config."
         fi
+        bash -c '
+        cat <<EOF >> $GIT_ROOT/$git_provider/$org_name/config
+        Host $git_provider
+          HostName $git_provider
+          User git
+          IdentityFile $GIT_ROOT/$git_provider/$org_name/key.pub
+          IdentitiesOnly yes
+        EOF
+        '
+        echo "Created ssh config."
