✨ feat(git): Update Git configuration for 1Password SSH Agent and improve WSL compatibility
- Modified the Git configuration tasks to utilize 1Password SSH Agent for commit signing on Windows.
- Added a new task for signing commits using the 1Password SSH Agent, enhancing security and usability.
- Updated WSL task descriptions and improved username retrieval method for better compatibility across environments.
- Standardized file paths to use forward slashes for consistency in Windows configurations.

diff --git a/apps/1password.ssh.yaml b/apps/1password.ssh.yaml
--- a/apps/1password.ssh.yaml
+++ b/apps/1password.ssh.yaml
@@ -121,3 +121,35 @@ tasks:
         echo "1Password SSH agent toml file has been created at $toml_file."
         echo ""
 
+  ssh-sign:windows:
+    platforms: [windows]
+    internal: true
+    cmds:
+      - |
+        username="{{ env "USERNAME" }}"
+        echo "Username: $username"
+        op_ssh_sign_exe_path=""
+        if [ -f C:/Users/$username/AppData/Local/1Password/app/8/op-ssh-sign.exe ]; then
+          op_ssh_sign_exe_path="C:/Users/$username/AppData/Local/1Password/app/8/op-ssh-sign.exe"
+        else
+          echo "ERROR: op-ssh-sign.exe not found (user: $username)"
+          exit 1
+        fi
+        echo "Configuring Git to use 1Password SSH Agent..."
+        git config --global gpg.ssh.program "$op_ssh_sign_exe_path"
+        git config --global gpg.format ssh
+        git config --global commit.gpgsign true
+        echo "Git configured to use 1Password SSH Agent and enabled commit signing globally."
+        echo ""
+
+  ssh-sign:
+    desc: "[1PASSWORD:SSH] Sign commits using 1Password SSH Agent"
+    cmds:
+      - |
+        if ! command -v git >/dev/null 2>&1; then
+          echo "ERROR: git command is not available"
+          echo "Please install git first."
+          exit 1
+        fi
+      - task: ssh-sign:windows
+        platforms: [windows]
